project-cosmo-sns/cosmos

src/components/Common/Buttons/DefaultButton/DefaultButton.module.scss
X
- 
- PR들 머지하고 보니까 오류 나길래 해당 오류 부분 수정했습니다~
-  SassError: Top-level selectors may not contain the parent selector "&"
-  X
- X
- X
=> [Fix] DefaultButton 상위 선택자 추가(빌드 오류 해결)

src/components/Common/AddContentPopOver/AddContentPopOver.module.scss, src/components/Common/Buttons/DefaultButton/DefaultButton.module.scss, src/components/Common/Buttons/FollowButton/FollowButton.module.scss, src/components/Common/Buttons/NoticeButton/NoticeButton.module.scss, src/components/Common/Buttons/SortDropdown/SortDropdown.module.scss, src/components/Common/ContentContainer/ContentContainer.module.scss, src/components/Common/Layout/NavigationBar/NavigationBar.module.scss, src/components/Common/Layout/SideBar/SideBar.module.scss, src/components/Common/SearchInput/SearchInput.module.scss, src/components/Post/CategoryFlag/CategoryFlag.module.scss, src/components/Profile/ProfileHeader.module.scss, src/pages/write/PostWritePage.module.scss, src/styles/globals.scss
- 컬러 변수명 오타 수정했는데 사용하는 곳에서 수정안된 부분들 때문에 빌드오류발생해서 수정해서 PR올립니다!
=> [Fix] 빌드 오류 해결

src/components/Common/Buttons/ToggleButton/ToggleButton.module.scss, src/components/Common/Buttons/ToggleButton/index.tsx, src/components/Common/Layout/Modal/index.tsx, src/components/Common/Layout/Notification/NotificationModal/NotificationModal.module.scss, src/components/Common/Layout/Notification/NotificationModal/index.tsx, src/components/Common/Layout/Notification/index.tsx
- 알림 모달 추가
- 토글 추가
- 모달... width 조정을 어떻게 해야하나 고민하다 일단 올립니다
-  일단!!!! 머지해놓는게 좋을것같아서 올려놓습니다. 여러가지 개선할 부분이 많습니다 (...)
- 검색...!!! 화면이 아직..미완성이네요 ^_ㅜ................... 일요일 안에 작업해서 PR 올리겠습니다 죄송함다 😥
- 검색
- 여러가지 개선... (반응형/코드정리/상세 조정)
-
=> [feat] 알림 모달 추가, 토글 버튼 추가

src/components/Common/Layout/Notification/NotificationModal/NotificationModal.module.scss, src/components/Common/Layout/Notification/NotificationModal/index.tsx, src/components/Common/SearchInput/SearchInput.module.scss, src/components/Common/SearchInput/index.tsx, src/hooks/useDebounce.ts, src/pages/_app.page.tsx
- useDebounce 훅 추가
- 서치 클리어 버튼 추가
- 알림 모달 스타일 수정(임시로 넣어놨던 코드 수정)
- x
-  원래 디바운스를 서치 input에 적용해봤다가, 엔터 쳤을때 검색어 넘겨줄거라 크게 의미가 있을것같지 않아서 (...) 훅만 추가해놨습니다.
- 딱히 많은것이 추가되지 않았습니다... 주말에 코드 리팩토링 한번 해볼게요!!
- 팝오버 수정
- 코드 리팩토링
=> [feat] useDebounce 훅 추가, 서치 클리어 버튼 추가, 알림 모달 스타일 수정

src/components/Common/AddContentPopOver/AddContentPopOver.module.scss, src/components/Common/Buttons/ToggleButton/ToggleButton.module.scss, src/components/Common/ContentContainer/ContentContainer.module.scss, src/components/Common/ContentContainer/index.tsx, src/components/Common/IconCollection/index.tsx, src/components/Common/Layout/Notification/Notification.module.scss, src/components/Common/Layout/Notification/NotificationItem/NotificationItem.module.scss, src/components/Common/Layout/Notification/NotificationItem/index.tsx, src/components/Common/Layout/Notification/NotificationModal/NotificationModal.module.scss, src/components/Common/Layout/Notification/index.tsx, src/components/Common/Layout/SideBar/SideBar.module.scss, src/components/Common/PopOverBox/PopOver.module.scss, src/components/Common/PopOverBox/index.tsx, src/components/Common/SearchInput/SearchInput.module.scss, src/components/Common/SearchInput/index.tsx, src/components/Common/TodayQuestion/TodayQuestion.module.scss, src/components/Common/TodayQuestion/index.tsx, src/components/Search/SearchAuthorProfile/SearchAuthorProfile.module.scss, src/pages/_app.page.tsx, src/utils/ModalScroll.ts
closed #60
closed #59
-
- 알림, 검색 디자인 적용
- popOver createPotal 적용
- 일단... 공통 레이아웃 백그라운드 blur 적용에서 예상치못하게 애를 먹었었습니다 ^_ㅜ;;;;;
- 팝오버 포탈 적용 하는 김에 모달 활성화시 스크롤이 해제되는 기능을 넣어보려서 여러가지 시도를 해봤는데, 몇가지 오류가 나서 일단 유틸 함수만 추가해놨습니다...
-  혹시나 충돌나는 부분이 있거나 잘못 적용한 부분이 있는지
- 검색, 알림 api가 나와서 기능 적용해보며 완성도 높여볼 생각입니다.
=> [feat] 알림, 검색 디자인 적용 / PopOver createPotal 적용

.gitignore, src/components/Common/CommentCard/api.ts, src/components/Feed/FeedCard/api.ts, src/components/Feed/FeedCard/index.tsx, src/components/Feed/FeedDetails/index.tsx, src/components/Feed/FeedList/index.tsx, src/pages/profile/index.page.tsx
- 
- 프로필 페이지에서 피드 목록을 서버사이드 렌더링으로 가져옵니다.
- 
-  
-
=> [Feature] 프로필 페이지 피드 목록 불러오기

src/components/Common/Layout/Notification/NotificationItem/NotificationItem.module.scss, src/components/Common/Layout/Notification/NotificationItem/index.tsx
- 피드 오픈 추가 ....
- 
-  감사합니다...^_^... 
-
-
=> [feat] 알림 피드인경우 모달 오픈 추가

src/components/Common/Layout/Layout.module.scss, src/components/Common/Toast/Toast.module.scss, src/components/Common/Toast/index.tsx, src/components/Profile/AuthForm/index.tsx, src/components/Profile/ProfileHeader/index.tsx, src/hooks/useToast.ts, src/pages/_app.page.tsx, src/pages/index.page.tsx, src/redux/store.ts, src/redux/toastSlice.ts, src/styles/Home.module.scss
- closed #96 
- 
- 
-  
- toast컴포넌트 훅으로 분리, 전역 설정
-
=> [feature] toast 전역으로 설정, toast hook 분리 

src/components/Common/Layout/Notification/NotificationItem/NotificationItem.module.scss, src/components/Common/Layout/Notification/NotificationItem/index.tsx, src/components/Common/Layout/Notification/NotificationModal/NotificationToggleButton/NotificationToggleButton.module.scss, src/components/Common/Layout/Notification/NotificationModal/NotificationToggleButton/index.tsx, src/components/Common/Layout/Notification/NotificationModal/index.tsx, src/components/Common/Layout/Notification/index.tsx, src/components/Search/SearchAuthorProfile/SearchAuthorProfile.module.scss, src/components/Search/SearchAuthorProfile/index.tsx, src/hooks/useFollowClick.ts
- 알림UI깨짐 수정했습니다.....
- 알림 무한스크롤 적용
- 사용자 검색 화면 팔로우 로직 수정해주신것 따라서 수정했습니다! 
- 맞다. 알림 설정 api 추가해놨습니다 
- 
-  
- 검색 화면 무한스크롤
- 오늘의 질문 api 후다닥 붙이기 
- 시간되면 모달 관련 추가기능 붙이기...
-
=> [fix] 알림 UI 깨짐 수정, 무한스크롤 적용 & 사용자 검색 화면 버그 수정

src/api/authorization.ts, src/components/Common/AddContentPopOver/index.tsx, src/components/Common/Layout/SideBar/index.tsx, src/components/Common/LoginModal/index.tsx, src/components/Common/Toast/index.tsx, src/components/Feed/CreateFeed/index.tsx, src/components/Profile/AuthForm/index.tsx, src/hooks/useInfiniteScroll.ts, src/hooks/useToast.ts, src/pages/_app.page.tsx, src/redux/loginModalSlice.ts, src/redux/store.ts, src/redux/toastSlice.ts
- closed #98 
- 컴포넌트마다 401에러 처리할 수 있도록 로그인모달 dispatch사용해서 전역으로 바꿨는데 이상하면 알려주세요
- 
-  api요청 함수에 에러처리 하는 곳에 dispatch(openLoginModal()) 넣으시면 적용될 겁니다..? 아마도?
-
-
=> [feat] 401에러핸들링 로그인모달 사용할 수 있도록 설정  

src/api/authorization.ts, src/api/member.ts, src/components/Common/AddContentPopOver/index.tsx, src/components/Common/Layout/SideBar/index.tsx, src/components/Common/Toast/index.tsx, src/components/Profile/AuthForm/index.tsx, src/components/Profile/ProfileHeader/index.tsx, src/pages/test/index.page.tsx, src/pages/write/index.page.tsx
- closed #64 
- 
- 
-  테스트 한번씩 부탁드립니다. 
- 프로필에 인증이랑 인증폼 연결했습니다
- 데이터도 잘 가는 것 같아요 
- 유정님 너무너무 감사드려요 
-
=> [Feature] 회원 인증 폼 연결 

src/api/member.ts, src/components/Feed/CreateFeed/CreateFeed.module.scss, src/components/Feed/CreateFeed/index.tsx, src/components/Feed/FeedCard/index.tsx
- #47 
- 이미지와 함께 피드를 생성하기 위해 
- 이미지 올려놓고 글을 작성하면 버벅거림
- 훅폼을 굳이 썻어야했을까 
- 피드 생성할때, 폼 벨류 상태 / 이미지 url 상태 / 이미지 파일 상태 
여러 상태들을 만들어서 처리해줬는데 과연 이것이 잘한 방법일까요
- 피드 상세에서 편집 기능 구현
- 피드 ui 수정 
- 피드 요청 후 리패치 
- 피드 QA 피드백 
- 피드백 수정
=> [Feat] 피드 생성하기 

src/components/Common/Layout/Modal/ModalPortal.tsx, src/components/Common/Layout/Modal/index.tsx, src/components/Common/SearchInput/SearchInput.module.scss, src/components/Common/TodayQuestion/TodayQuestion.module.scss
- 이전 pr에서 모달 관련으로 스크롤 없애기 + 아웃사이드 클릭 적용했는뎅 첫 렌더링시 스크롤이 그냥 안보이는 현상이 있어서 좀 수정했습니다
- 디자인 검수대로 서치바, 오늘의 질문쪽 값 수정했습니다~ 
- 
-  
-
-
=> [Fix] 모달 스크롤 버그 수정, 디자인 검수대로 스타일 변경

src/components/Common/Layout/Notification/index.tsx
closed #148 
- 알림 미인증 사용자 토스트 처리 추가
- 그냥 제가 바보엿읍니다. 재송합니다.
-  이거 말고 검색 미로그인 / 인증대기 사용자 검색 막는거를 해야합니다.
-  api 추가되면 알림 팔로우 버튼 로직 추가 부탁드립니다!! 감사합니다. 👀🙏🔥
- PPT를깎겠습니다...
=> [Fix] 알림 미인증 사용자 토스트 처리 추가

.eslintrc.json, src/components/Common/IconCollection/index.tsx, src/components/Post/Markdown/index.tsx, src/components/Profile/MyPostList/MyPostList.module.scss, src/components/Profile/ProfileContent/EmptyContent.module.scss, src/pages/profile/MemberDataContainer.module.scss, src/pages/profile/index.page.tsx
- 프로필 쪽 깨지는 UI만 수정했습니다! 배포하기 전에 추가하려고 코드 뭐 없는데 일단 올립니더 ㅎ.ㅎ.
- 
-  
-
-
=> [Design] 프로필 페이지 디자인 수정

src/components/Profile/AuthForm/index.tsx
- 
- 
- 
-  모달 내부 클릭하면 닫히는거 수정햇어여 어프루브 플리즈
-
-
=> 🐛 fix : 인증 모달 클릭 시 닫히는 문제 수정

src/@types/type.ts, src/api/admin.ts, src/api/authorization.ts, src/components/Admin/AdminDetail/index.tsx, src/components/Profile/AuthForm/AuthForm.module.scss, src/components/Profile/AuthForm/index.tsx, src/constants/generationRegex.ts
- 
- 
- 
-  
- AuthForm에 이름 추가 
-
=> [Feat] AuthForm에 name 인풋 추가

src/components/Common/SearchInput/SearchInput.module.scss, src/components/Post/PostContent/PostContent.module.scss, src/components/Post/PostContent/index.tsx, src/components/Post/ScrapButton/ScrapButton.module.scss, src/components/Post/ScrapButton/index.tsx, src/components/Post/types.ts, src/hooks/useSendScrapRequest.ts, src/pages/write/index.page.tsx
- 포스트 작성 및 수정 시 공백 입력 막았습니다
- 모바일에서 유튜브 영상 퍼가기 iframe으로 추가했을 때 재생 화면 깨지던 부분 수정했습니다
- 모바일에서 검색창이 로고와 겹쳐서 크기 줄였습니다
- 포스트 스크랩 기능 추가했습니다.
- 
- 스크랩 숫자도 보여줘야할지, 내 포스트도 스크랩 가능하게 할지 얘기해보면 좋을 것 같습니다
(현재는 내 포스트일 경우 수정, 삭제 버튼이 보이고 다른사람 포스트일 경우 스크랩 버튼이 보이도록 했습니다) 
-
-
=> [Feat] 포스트 스크랩 기능 추가 및 버그 수정

src/components/Feed/EditFeed/index.tsx, src/components/Feed/FeedDetails/index.tsx
=> [test commit]

src/components/Feed/CreateFeed/index.tsx, vercel-ignore-step.sh
=> [test commit 3]
